<?xml version="1.0" encoding="utf-8"?><Database Name="QuizMahasiswa" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-CFKLQAHI\SQLEXPRESS;Initial Catalog=QuizMahasiswa;Integrated Security=True" SettingsObjectName="MasterBarang030.Properties.Settings" SettingsPropertyName="QuizMahasiswaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_barang" Member="tbl_barangs">
    <Type Name="tbl_barang">
      <Column Name="id_barang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nama_barang" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="harga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stok" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nama_supplier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>